### ISSUE TITLE
dedicated storage network

### ISSUE THREAD

**Issue by rmkraus** [project-faros/cluster-manager#134]
Create an isolated network over the second 10 gig interface for storage traffic.

**Comment by mulbc** [comment]
[this doc](https://docs.google.com/document/d/1VlEa-HGGHF_XrWfq01HkIo2ISJcPJes4O3DFC7xAFMo/) explains how to configure ODF with Multus on a separate interface.

I have tried this out on the EL8000 with success by using the second NIC and tested with Ripsaw that Storage was using the separate interface.
The private ODF network was not used in this case.

**Comment by rmkraus** [comment]
Superseded by #147
