### ISSUE TITLE
deploy container-storage Failed

### ISSUE THREAD

**Issue by neama12** [project-faros/cluster-manager#140]
Deploying OCS (farosctl deploy container-storage)  fails on first run with below error. Verified storagecluster did not get created therefore the check is failing.  Rerunning deploy of container-storage creates the StorageCluster and finishes successfully. 

STEP 1: QUERY CLUSTER FACTS

Playbook run took 0 days, 0 hours, 0 minutes, 6 seconds

? Select nodes to use for storage  done (3 selections)
? Select the block devices to use for storage  done (12 selections)
STEP 1: INSTALL OPENSHIFT LOCAL STORAGE
ensure project exists localhost
ensure operatorgroup exists localhost
ensure subscription exists localhost
ensure storage nodes are labeled localhost
create localvolume object localhost

STEP 1: INSTALL OPENSHIFT CONTAINER STORAGE
ensure project exists localhost
ensure operatorgroup exists localhost
ensure subscription exists localhost
ensure storagecluster exists
failed: localhost: Failed to find exact match for ocs.openshift.io/v1.StorageCluster by [kind, name, singularName, shortNames]

deploy container-storage Failed

oc get StorageCluster
No resources found in openshift-storage namespace.

**Comment by rmkraus** [comment]
released in 4.7.1
