### ISSUE TITLE
Faros node name error after bastion host renamed

### ISSUE THREAD

**Issue by miktaylor3** [project-faros/cluster-manager#144]
I did an install but forgot to name it correctly the 1st time (bastion.rdc100.lan).  So II renamed the bastion host (bastion.edge.rdc100.lan) and re-ran the install and it worked, but one of the nodes (node-7) didn’t pick up the new name. 

farosadmin@bastion ~]$ oc get nodes
NAME                     STATUS   ROLES           AGE   VERSION
node-3.edge.rdc100.lan   Ready    master,worker   56m   v1.20.0+2817867
node-5.edge.rdc100.lan   Ready    master,worker   56m   v1.20.0+2817867
node-7.rdc100.lan        Ready    master,worker   56m   v1.20.0+2817867

I renamed the host by editing /etc/hostname and rebooting

[named.Jun23.txt](https://github.com/project-faros/cluster-manager/files/6704240/named.Jun23.txt)

**Comment by rmkraus** [comment]
Have you run any `farosctl apply` commands on this cluster since the cluster install with the wrong name?

Also, could you paste the contents of `/var/lib/named/zone.8.168.192.in-addr.arpa`

**Comment by miktaylor3** [comment]
Note: I updated to the bastion to RH 8.4 with the last install, 

I re-ran the cluster install since the initial problem.  Now it looks like it has dropped “edge” all together from the name.   I can update and re-install if needed, this is the DISA cluster that remains untouched. I will  change your  lab login to the 100 VLAN so you can connect to the host if it helps.  

[root@bastion etc]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)

[farosadmin@bastion default]$ hostname
bastion.edge.rdc100.lan

[farosadmin@bastion default]$ oc get nodes
NAME                STATUS   ROLES           AGE     VERSION
node-3.rdc100.lan   Ready    master,worker   4d22h   v1.20.0+2817867
node-5.rdc100.lan   Ready    master,worker   4d22h   v1.20.0+2817867
node-7.rdc100.lan   Ready    master,worker   4d22h   v1.20.0+2817867

The file you ask for is in /var/named/  (not  /var/lib/named/, no such directory), not sure if this is related to the 8.4 release. 

[root@bastion named]# pwd
/var/named

[root@bastion named]# cat zone.8.168.192.in-addr.arpa 
$TTL 1D
@ IN SOA ns.edge.rdc100.lan. edge.rdc100.lan. 1624476903 1D 1W 1W 3H;
@ IN NS ns.edge.rdc100.lan.
3.8.168.192.in-addr.arpa. IN PTR bootstrap.rdc100.lan.
4.8.168.192.in-addr.arpa. IN PTR node-3.rdc100.lan.
6.8.168.192.in-addr.arpa. IN PTR node-5.rdc100.lan.
8.8.168.192.in-addr.arpa. IN PTR node-7.rdc100.lan.
5.8.168.192.in-addr.arpa. IN PTR node-3-mgmt.rdc100.lan.
7.8.168.192.in-addr.arpa. IN PTR node-5-mgmt.rdc100.lan.
9.8.168.192.in-addr.arpa. IN PTR node-7-mgmt.rdc100.lan.
1.8.168.192.in-addr.arpa. IN PTR bastion.rdc100.lan.
2.8.168.192.in-addr.arpa. IN PTR loadbalancer.rdc100.lan.
100.8.168.192.in-addr.arpa. IN PTR cm.rdc100.lan.
101.8.168.192.in-addr.arpa. IN PTR jump.rdc100.lan.
102.8.168.192.in-addr.arpa. IN PTR bastion-ilo.rdc100.lan.
3.8.168.192.in-addr.arpa. IN PTR bootstrap.edge.rdc100.lan.
4.8.168.192.in-addr.arpa. IN PTR node-3.edge.rdc100.lan.
6.8.168.192.in-addr.arpa. IN PTR node-5.edge.rdc100.lan.
8.8.168.192.in-addr.arpa. IN PTR node-7.edge.rdc100.lan.
5.8.168.192.in-addr.arpa. IN PTR node-3-mgmt.edge.rdc100.lan.
7.8.168.192.in-addr.arpa. IN PTR node-5-mgmt.edge.rdc100.lan.
9.8.168.192.in-addr.arpa. IN PTR node-7-mgmt.edge.rdc100.lan.
1.8.168.192.in-addr.arpa. IN PTR bastion.edge.rdc100.lan.
2.8.168.192.in-addr.arpa. IN PTR loadbalancer.edge.rdc100.lan.
100.8.168.192.in-addr.arpa. IN PTR cm.edge.rdc100.lan.
101.8.168.192.in-addr.arpa. IN PTR jump.edge.rdc100.lan.
102.8.168.192.in-addr.arpa. IN PTR bastion-ilo.edge.rdc100.lan.
101.8.168.192.in-addr.arpa. IN PTR cm.edge.rdc100.lan.
100.8.168.192.in-addr.arpa. IN PTR jump.edge.rdc100.lan.

**Comment by miktaylor3** [comment]
I re-installed the cluster today with the latest update and everything looks correct. So probably OK to close this issue

**Comment by rmkraus** [comment]
Released in 4.7.2
