### ISSUE TITLE
farosctl get ip-addresses not working 

### ISSUE THREAD

**Issue by miktaylor3** [project-faros/cluster-manager#151]
Looks like the latest update did something to the "farosctl get ip-addresses" 

This is from a running cluster, everything is reporting as unreachable 

[farosadmin@bastion ~]$ farosctl get ip-addresses
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Host                   | IP Address     |  MAC Address      |  Reachable (SSH)
--------------------------------------------------------------------------------
                       |                |                   |
bastion                | 192.168.8.1    | null              | - NO
bootstrap              | 192.168.8.3    | null              | - NO
dhcp                   | 192.168.8.1    | null              | - NO
dns                    | 192.168.8.1    | null              | - NO
lan                    | 192.168.8.1    | null              | - NO
loadbalancer           | 192.168.8.2    | null              | - NO
localhost              | null           | null              | - NO
node-3                 | 192.168.8.4    | 94:40:c9:f3:1a:31 | - NO
node-3-mgmt            | 192.168.8.5    | 94:40:c9:f3:1a:2b | - NO
node-5                 | 192.168.8.6    | 94:40:c9:f3:1a:af | - NO
node-5-mgmt            | 192.168.8.7    | 94:40:c9:f3:1a:a9 | - NO
node-7                 | 192.168.8.8    | 94:40:c9:f3:1c:61 | - NO
node-7-mgmt            | 192.168.8.9    | 94:40:c9:f3:1c:5b | - NO
wan                    | 192.168.100.20 | null              | - NO
cm                     | 192.168.8.100  | 94:40:c9:20:d2:a4 | - NO
jump                   | 192.168.8.101  | 00:23:7d:e0:01:e4 | - NO
bastion-ilo            | 192.168.8.102  | 94:40:c9:f3:1a:86 | - NO
--------------------------------------------------------------------------------

[farosadmin@bastion ~]$ ping 192.168.8.4
PING 192.168.8.4 (192.168.8.4) 56(84) bytes of data.
64 bytes from 192.168.8.4: icmp_seq=1 ttl=64 time=0.175 ms
64 bytes from 192.168.8.4: icmp_seq=2 ttl=64 time=0.127 ms
64 bytes from 192.168.8.4: icmp_seq=3 ttl=64 time=0.203 ms
^C

**Comment by rmkraus** [comment]
released in 4.7.3
