### ISSUE TITLE
failed: bastion: Unable to start service tangd.socket: Job for tangd.socket failed

### ISSUE THREAD

**Issue by neama12** [project-faros/cluster-manager#158]
Issue : Farosctl create install-repo fails to run
Error : failed: bastion: Unable to start service tangd.socket: Job for tangd.socket failed
           SELinux is preventing systemd from name_bind access on the tcp_socket port 8082

If port 8082 is already defined in a different name_bind "semanage port -a"  will fail and should be "semanage port -m" instead

**Comment by rmkraus** [comment]
released in 4.7.3
