### ISSUE TITLE
Farosctl Destroy fails to wipe cluster nodes

### ISSUE THREAD

**Issue by neama12** [project-faros/cluster-manager#159]
Issue: New functionality added to Farosctl but dependencies do not get updated with "Farosctl upgrade" 

In the case of farosctl destroy, "wipe.ign" was not added httpd server until install-repos was run. Enhancement request to possibly include any dependencies for "new" functionality that is idempotent with "farosctl upgrade"

**Comment by rmkraus** [comment]
Thanks and noted. Per our discussion today, we'll keep an eye on this going forward.
