### ISSUE TITLE
oc login needed for storageclass default set

### ISSUE THREAD

**Issue by lincolnhpe** [project-faros/cluster-manager#78]
Please include in storage setup or connecting to cluster doc
:
#farosctl get oc-login
(change to match) #oc login -u kubeadmin -p "PASSWORD" https://api.openshift.psdc.lan:6443

otherwise you get this error 

[psdcadmin@bastion .config]$ oc patch storageclass ocs-storagecluster-cephfs -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

**Comment by lincolnhpe** [comment]
Make easier to understand storage entry  

Then configure spec.storage to create a PersistentVolumeClaim.

After making these changes, watch the operator status indicator on the OpenShift console. When the indicator goes green and doesn’t show anymore cluster operators pending, the configuration change is complete.

Here is an example config.imageregistry.operator.openshift.io/cluster resource.

apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
  - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  logging: 2
  managementState: Managed
  proxy: {}
  replicas: 1
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  rolloutStrategy: RollingUpdate
  storage:
    pvc:
      claim:

**Comment by lincolnhpe** [comment]
Please be more descriptive as to where I need to look in Openshift console. Assume I am not an Openshift Admin knowing where to look. 

After making these changes, watch the operator status indicator on the OpenShift console. When the indicator goes green and doesn’t show anymore cluster operators pending, the configuration change is complete.

**Comment by lincolnhpe** [comment]
-- deploy nvidia-drivers
|
-----------------------------------------------------------------------------------------------------------------------------------------
STEP 1: INSTALL NVIDIA GPU DRIVERS
ensure project exists localhost
ensure operatorgroup exists localhost
ensure nfd subscription exists localhost
ensure nvidia subscription exists localhost
lookup install plan
failed: localhost: The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'installplan'

The error appears to be in '/app/playbooks/deploy.d/nvidia-drivers/nvidia-drivers.yml': line 98, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: lookup install plan
      ^ here


Playbook run took 0 days, 0 hours, 0 minutes, 38 seconds



deploy nvidia-drivers Failed




install-plan nvidia-support Failed

**Comment by rmkraus** [comment]
These issues should all be addressed now.
