### ISSUE TITLE
beacon02 installation issues

### ISSUE THREAD

**Issue by johnsimcall** [project-faros/cluster-manager#80]
During the installation of `beacon02` we observed that:

- [x] The `bootstrap_bastion.sh` script should check that the `wget` and `checkmodule` commands are installed.  If not, then the script should `dnf -y install checkpolicy wget`

- [x] The `farosctl install-plan cluster` command should not allow `SSH to  Bastion` to be disabled.  Our installation froze during the `configure ingress ssh to bastion` task.

- [x] Conflict between ifcfg-scripts and nmcli profiles.  Resolved via `nmcli con mod faroslan ipv4.gateway ""`
- - [x] Please document that NetworkManager is required (not ifcfg-scripts)
- - [x] Consider changing [this line](https://github.com/project-faros/cluster-manager/blob/47ff2a3fae0bb87344d46a32acd72790a58646cc/app/roles/router/tasks/wan_config.yaml#L21)  to just do an `nmcli con up NAME`

**Comment by rmkraus** [comment]
I'm not going to address the second item for now as it wasn't what caused our issues and the config system is going to be refactored soon anyway. The rest have been fixed and addressed.
